### PR TITLE
hwcomposer: Cleaner solution to deal with QCOM_BSP, QTI_BSP and QCOM_…

### PR DESCRIPTION
**Pull request by Herrie82**
…HARWARE

This was previously done by patches that were applied. Having this as configs is a nicer way of doing it.

Removes the need of nasty hacks such as: https://github.com/webOS-ports/meta-webos-ports/blob/herrie/qt5qpa/meta-luneos/recipes-qt/qt5/qt5-qpa-hwcomposer-plugin/0002-Add-QCOM_BSP-define-switch.patch

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by NotKit** [comment]
Is this needed for Qualcomm devices? SailfishOS and Halium add #define QCOM_BSP 1
#define QTI_BSP 1 to config.h in android-headers.

**Comment by Herrie82** [comment]
I cannot find this in android-headers for Halium. I'm not sure where to find the ones SFOS? Both LuneOS and AsteroidOS use a patch currently as per https://github.com/AsteroidOS/meta-asteroid/blob/30a40d156b89ee4f2437ce4fd3addb3ffba7cb33/recipes-qt/qt5/qt5-qpa-hwcomposer-plugin/0002-Add-QCOM_BSP-define-switch.patch and above link already ;)

**Comment by Herrie82** [comment]
This is basically needed for Qualcomm devices using caf sources. From what I've been told by @bhush9 this is pretty much everything non-Nexus that uses Qualcomm. These flags would need to be added to everything that uses the android-headers. For LuneOS this is: libhybris, pulseaudio-modules-droid, qt5-qpa-hwcomposer-plugin, qtscenegraph-adaptation, qtsensors-sensorfw-plugin, sensorfw and nyx-modules-hybris.

**Comment by Herrie82** [comment]
You were right, we're now implementing a similar solution in LuneOS so this is not required anymore for each component. As per https://github.com/shr-distribution/meta-smartphone/pull/58/files and https://github.com/webOS-ports/meta-webos-ports/pull/279

**Pull request closed without merging**
